apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: broken-link
message: "App for testing docs.csc.fi and report broken links"
metadata:
  annotations:
    description: "Check links broken"
  name: broken-link
parameters:
- name: GITHUB_URL
  description: URL of the GitHub repo where the app is located
  required: true
  value: https://github.com/Socuz/broken-link.git

- name: GITHUB_BRANCH
  description: Branch used in the GitHub repo
  required: true
  value: rahti3

- name: EMAIL_RECIPIENT
  description: Email address of the recipient(s)
  required: true

objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: broken-link
    name: broken-link-bc
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: broken-link:latest
    source:
      git:
        ref: ${GITHUB_BRANCH}
        uri: ${GITHUB_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: EMAIL_RECIPIENT
          value: ${EMAIL_RECIPIENT}
        from:
          kind: ImageStreamTag
          name: python:3.9
          namespace: openshift
      type: Source
    triggers:
      - type: ImageChange
      - type: ConfigChange

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: broken-link
    name: broken-link
  spec:
    lookupPolicy:
      local: true

- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: broken-link-cj
  spec:
    schedule: '0 3 2 * *'
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: broken-link
                image: broken-link
            restartPolicy: OnFailure