apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: broken-link
message: "App for testing docs.csc.fi and report broken links"
metadata:
  annotations:
    description: "Check links broken"
  name: broken-link
parameters:
- name: NAMESPACE
  description: Name of your Rahti namespace/project
  required: true

- name: GITHUB_URL
  description: URL of the GitHub repo where the app is located
  required: true
  value: https://github.com/Socuz/broken-link.git

- name: GITHUB_BRANCH
  description: Branch used in the GitHub repo
  required: true
  value: rahti3

objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: broken-link
    name: broken-link
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: broken-link:latest
    source:
      git:
        ref: ${GITHUB_BRANCH}
        uri: ${GITHUB_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.9
          namespace: openshift
      type: Source
    triggers:
      - type: ImageChange
      - type: ConfigChange
  status: {}

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: broken-link
    name: broken-link
  status: {}

- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: broken-link
  spec:
    schedule: '0 3 2 * *'
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: broken-link
                image: docker-registry.rahti.csc.fi/${NAMESPACE}/broken-link:latest
            restartPolicy: OnFailure